### ISSUE TITLE
`source zsh-syntax-highlighting.zsh` should be last

### ISSUE THREAD

**Issue by jonathonf** [Chrysostomus/manjaro-zsh-config#2]
As per https://github.com/zsh-users/zsh-syntax-highlighting:

> FAQ
> Why must zsh-syntax-highlighting.zsh be sourced at the end of the .zshrc file?
> 
> zsh-syntax-highlighting.zsh wraps ZLE widgets. It must be sourced after all custom widgets have been created (i.e., after all zle -N calls and after running compinit). Widgets created later will work, but will not update the syntax highlighting.

**Comment by Chrysostomus** [comment]
Thank you, I only knew it needed to be after history substring search. I'll just move plugins to the end.

**Comment by Chrysostomus** [comment]
Fixed.
