### ISSUE TITLE
With this config I got hooked :)

### ISSUE THREAD

**Issue by fhdk** [Chrysostomus/manjaro-zsh-config#8]
I just had to reinstall my machine - stupid mistake.

The first thing to do is 

    pacman -S guake manjaro-zsh-config
    chsh -s /bin/zsh fh

But I cannot find why my gnome-terminal totally disregards `Home` and `End` while Guake Terminal works as expected.

    ~ >>> gnome-terminal --version                                              [1]
    GNOME Terminal 3.22.1 Using VTE version 0.46.1 +GNUTLS

Kinda hoped you could point me in the right direction.

**Comment by Chrysostomus** [comment]
Most likely it sees home/end differently. Use 

     cat 
Without arguments to see what your terminal sees when you press those keys, and bind that in your .zshrc.

**Comment by fhdk** [comment]
Neat - thanks for the tip :smile:
